spring:
  application:
    name: config-server
  profiles:
    active: git
  # active: native  # native -> read from file system
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/latifzouliga/Ticketing-Project-Microservices-Config
          default-label: main
          username: latifzouliga
          password: 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
      fail-fast: true

server:
  port: 8888